Password Hashing Upgrade
open-osp/Open-O pull request #11
Opened 2024-12-24 00:38 UTC by chitrankd

This PR introduces robust password security enhancements by migrating from a custom deprecated SHA based hashing algorithm to BCrypt, leveraging Spring Security's `PasswordEncoder` framework.

* **BCryptPasswordEncoder Adoption:** The core change replaces the custom SHA hashing with `BCryptPasswordEncoder`, a significantly more secure algorithm. This is implemented via the new `PasswordHashHelper` and `Deprecated_SHA_PasswordEncoder` classes.  The `PasswordHashHelper` centralizes password encoding logic, utilizing `BCryptPasswordEncoder` by default while maintaining compatibility with existing SHA hashes through `Deprecated_SHA_PasswordEncoder`.

* **DelegatingPasswordEncoder Integration:**  The `PasswordHashHelper` utilizes `DelegatingPasswordEncoder`, which gracefully handles multiple encoding mechanisms. This allows the system to seamlessly manage both newly created BCrypt hashes and legacy SHA hashes while authentication and migration.

* **`SecurityManager`**: This class is updated to leverage the new `PasswordHashHelper` and `EncryptionUtils` methods. The `encodePassword`, `validatePassword`, `matchesPassword`, and `upgradeSavePasswordHash` methods now utilize bcrypt, improving security.

* **`pom.xml`**:  the `spring-security-crypto` dependency is added, providing the necessary classes like `BCryptPasswordEncoder` and `DelegatingPasswordEncoder`.

* Replacing old SHA hashing with `SecurityManager` wherever required throughout the application.

These changes enhance the password security of the application by using a strong, industry-standard password hashing algorithm. The inclusion of a password upgrade mechanism ensures a smooth transition for existing users without requiring them to reset their passwords immediately.  The use of Spring Security's `DelegatingPasswordEncoder` future-proofs the application by allowing for easy adoption of new password hashing algorithms.

2025-01-07 22:46 UTC, warrendennis requested changes
Process to change login information fails when new password hash is used.

To replicate;

1). login 
2). observe that the user password is now hashed with new method
3). go to: Administration / User Management / Search Edit Delete Security Records 
4). search for login record
5). Select search result

Outcome:

Error 500.  
The full stack trace is clobbered so I'm not able to tell where the error occurs.  
It does only happen after the password hash is updated after first login and/or after changing the password via user preferences.

Desired outcome: 

Display of a user interface for updating the login record data - including password changes.

2025-01-10 20:03 UTC, kk-chung commented
@kk-chung    please test this PR

2025-01-23 00:49 UTC, warrendennis commented
Thank you for trying Keith.  We need to move on.

2025-01-23 00:51 UTC, warrendennis approved these changes
Concerns found during bench testing were issues with the testers bench configuration.  All tests passed.

2025-01-23 00:56 UTC, merged

2025-01-24 14:43 UTC, kk-chung commented
@warrendennis    to briefly close the loop, I can confirm that sanity testing on this PR inclusive of using both the SOAP and REST API has now been completed; no issues identified.